### ISSUE TITLE
Edit Value and export

### ISSUE THREAD

**Issue by Lordrinium** [lutzroeder/resourcer#1]
Welcome!

I'm trying to use this great app and I can't edit the values. I want to use the application to translate a program. Can this be solved?
Thanks!

**Comment by lutzroeder** [comment]
Select item and edit value in the bottom window.

**Comment by Lordrinium** [comment]
Thanks!

In the meantime, I found out how the program works and it works great.

However, I would like to ask for help.

There is a resource.dll file that I want to edit, is there a way to do this?
